/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2021-05-03 10:10:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.basic;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Login V9</title>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\"\r\n");
      out.write("\thref=\"../resource_login/images/icons/favicon.ico\" />\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"../resource_login/vendor/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"../resource_login/fonts/font-awesome-4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"../resource_login/fonts/iconic/css/material-design-iconic-font.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"../resource_login/vendor/animate/animate.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"../resource_login/vendor/css-hamburgers/hamburgers.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"../resource_login/vendor/animsition/css/animsition.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"../resource_login/vendor/select2/select2.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"../resource_login/vendor/daterangepicker/daterangepicker.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"../resour\tce_login/css/util.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"../resource_login/css/main.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/84865ac036.js\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("/* The Modal (background) */\r\n");
      out.write(".modal {\r\n");
      out.write("\tdisplay: none; /* Hidden by default */\r\n");
      out.write("\tposition: fixed; /* Stay in place */\r\n");
      out.write("\tz-index: 1; /* Sit on top */\r\n");
      out.write("\tleft: 0;\r\n");
      out.write("\ttop: 0;\r\n");
      out.write("\twidth: 100%; /* Full width */\r\n");
      out.write("\theight: 100%; /* Full height */\r\n");
      out.write("\toverflow: auto; /* Enable scroll if needed */\r\n");
      out.write("\tbackground-color: rgb(0, 0, 0); /* Fallback color */\r\n");
      out.write("\tbackground-color: rgba(0, 0, 0, 0.4); /* Black w/ opacity */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Modal Content/Box */\r\n");
      out.write(".modal-content {\r\n");
      out.write("\tbackground-color: #fefefe;\r\n");
      out.write("\tmargin: 15% auto; /* 15% from the top and centered */\r\n");
      out.write("\tpadding: 20px;\r\n");
      out.write("\tborder: 1px solid #888;\r\n");
      out.write("\twidth: 80%; /* Could be more or less, depending on screen size */\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container-login100\"\r\n");
      out.write("\t\tstyle=\"background-image: url('../resource_login/images/EPL.png');\">\r\n");
      out.write("\t\t<div class=\"wrap-login100 p-l-55 p-r-55 p-t-80 p-b-30\">\r\n");
      out.write("\t\t\t<form class=\"login100-form validate-form\" action=\"/LoginProc.do\"\r\n");
      out.write("\t\t\t\tmethod=\"post\">\r\n");
      out.write("\t\t\t\t<span class=\"login100-form-title p-b-37\"> Sign In </span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"wrap-input100 validate-input m-b-20\"\r\n");
      out.write("\t\t\t\t\tdata-validate=\"Enter email\">\r\n");
      out.write("\t\t\t\t\t<input class=\"input100\" type=\"text\" name=\"id\" id=\"userId\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"Email\"> <span class=\"focus-input100\"></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"wrap-input100 validate-input m-b-3\"\r\n");
      out.write("\t\t\t\t\tdata-validate=\"Enter password\">\r\n");
      out.write("\t\t\t\t\t<input class=\"input100\" type=\"password\" name=\"pwd\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"password\"> <span class=\"focus-input100\"></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"text-right m-b-15\" style=\"font-size: 13px\">\r\n");
      out.write("\t\t\t\t\t<span onClick=\"open_pop();\" class=\"m-r-10 hov1\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"cursor: pointer\">Forgot password</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"container-login100-form-btn\">\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\" class=\"login100-form-btn\">Log In</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"text-center p-t-57 p-b-20\">\r\n");
      out.write("\t\t\t\t\t<span class=\"txt1\"> Or login with </span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"flex-c p-b-112\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"login100-social-item\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-facebook-f\"></i>\r\n");
      out.write("\t\t\t\t\t</a> <a href=\"#\" class=\"login100-social-item\"> <img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"../resource_login/images/icons/icon-google.png\" alt=\"GOOGLE\">\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"text-center\">\r\n");
      out.write("\t\t\t\t\t<a href=\"SignUp.do\" class=\"txt2 hov1\"> Sign Up </a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"myModal\" class=\"modal\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Modal content -->\r\n");
      out.write("\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t<p style=\"text-align: center;\">\r\n");
      out.write("\t\t\t\t\t<span style=\"font-size: 14pt;\"><b><span\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"font-size: 24pt;\">Get new password</span></b></span>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"close\" onClick=\"close_pop();\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fas fa-times\"></i>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br> <br>\r\n");
      out.write("\t\t\t<div class=\"row p-l-30 p-r-30\">\r\n");
      out.write("\t\t\t\t<input class=\"input100\" type=\"text\" name=\"email\" id=\"target_mail\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"enter Email\" style=\"width: 100%\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<div onClick=\"send();\"\r\n");
      out.write("\t\t\t\tstyle=\"cursor: pointer; background-color: #ACF6CA; text-align: center; padding-bottom: 10px; padding-top: 10px; margin: 0 20%; border-radius: 15px;\">\r\n");
      out.write("\t\t\t\t<span>Get Password&nbsp&nbsp<i class=\"far fa-paper-plane\"></i></span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t//팝업 Open 기능\r\n");
      out.write("\t\tfunction open_pop() {\r\n");
      out.write("\t\t\t$('#myModal').show();\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//팝업 Close 기능\r\n");
      out.write("\t\tfunction close_pop(flag) {\r\n");
      out.write("\t\t\t$('#myModal').hide();\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//임시 비밀번호 전송 -- 알림창 수정 필요\r\n");
      out.write("\t\tfunction send(){\r\n");
      out.write("\t\t\tvar email = $('#target_mail').val().trim();\r\n");
      out.write("\t\t\tif(email.match(/^([a-zA-Z0-9_\\-\\.]+)@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.)|(([a-zA-Z0-9\\-]+\\.)+))([a-zA-Z]{1,5}|[0-9]{1,3})(\\]?)$/) == null) {\r\n");
      out.write("\t\t\t\treturn alert(\"올바른 이메일을 입력해주세요\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"sendNewPwdProc.do\",\r\n");
      out.write("\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\tdata : {\"email\" : email},\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\tif (data == 0) {\r\n");
      out.write("\t\t\t\t\t\talert(\"회원정보가 없는 이메일 입니다.\");\t\r\n");
      out.write("\t\t\t\t\t}else if(data== 1){\r\n");
      out.write("\t\t\t\t\t\talert(\"임시 비밀번호가 발송 되었습니다.\");\r\n");
      out.write("\t\t\t\t\t\tclose_pop();\r\n");
      out.write("\t\t\t\t\t}else if(data == 2){\r\n");
      out.write("\t\t\t\t\t\talert(\"임시 비밀번호 발송에 실패했습니다.\");\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\talert(\"전산에 오류로 임시 비밀번호 변경을 실패했습니다.\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}}); // ajax 끝\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<!--===============================================================================================-->\r\n");
      out.write("\t<script src=\"../resource_login/vendor/jquery/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("\t<!--===============================================================================================-->\r\n");
      out.write("\t<script src=\"../resource_login/vendor/animsition/js/animsition.min.js\"></script>\r\n");
      out.write("\t<!--===============================================================================================-->\r\n");
      out.write("\t<script src=\"../resource_login/vendor/bootstrap/js/popper.js\"></script>\r\n");
      out.write("\t<script src=\"../resource_login/vendor/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<!--===============================================================================================-->\r\n");
      out.write("\t<script src=\"../resource_login/vendor/select2/select2.min.js\"></script>\r\n");
      out.write("\t<!--===============================================================================================-->\r\n");
      out.write("\t<script src=\"../resource_login/vendor/daterangepicker/moment.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"../resource_login/vendor/daterangepicker/daterangepicker.js\"></script>\r\n");
      out.write("\t<!--===============================================================================================-->\r\n");
      out.write("\t<script src=\"../resource_login/vendor/countdowntime/countdowntime.js\"></script>\r\n");
      out.write("\t<!--===============================================================================================-->\r\n");
      out.write("\t<script src=\"../resource_login/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
