/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2021-03-18 15:08:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <title>Soccer &mdash; Website by Colorlib</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../resource/fonts/icomoon/style.css\">\r\n");
      out.write("\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../resource/css/bootstrap/bootstrap.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../resource/css/jquery-ui.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../resource/css/owl.carousel.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../resource/css/owl.theme.default.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../resource/css/owl.theme.default.min.css\">\r\n");
      out.write("\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../resource/css/jquery.fancybox.min.css\">\r\n");
      out.write("\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../resource/css/bootstrap-datepicker.css\">\r\n");
      out.write("\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../resource/fonts/flaticon/font/flaticon.css\">\r\n");
      out.write("\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../resource/css/aos.css\">\r\n");
      out.write("\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../resource/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"site-wrap\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"site-mobile-menu site-navbar-target\">\r\n");
      out.write("      <div class=\"site-mobile-menu-header\">\r\n");
      out.write("        <div class=\"site-mobile-menu-close\">\r\n");
      out.write("          <span class=\"icon-close2 js-menu-toggle\"></span>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"site-mobile-menu-body\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <header class=\"site-navbar py-4\" role=\"banner\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"d-flex align-items-center\">\r\n");
      out.write("          <div class=\"site-logo\">\r\n");
      out.write("            <a href=\"index.html\">\r\n");
      out.write("              <img src=\"../resource/images/logo.png\" alt=\"Logo\">\r\n");
      out.write("            </a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"ml-auto\">\r\n");
      out.write("            <nav class=\"site-navigation position-relative text-right\" role=\"navigation\">\r\n");
      out.write("              <ul class=\"site-menu main-menu js-clone-nav mr-auto d-none d-lg-block\">\r\n");
      out.write("                <li class=\"active\"><a href=\"index.html\" class=\"nav-link\">Home</a></li>\r\n");
      out.write("                <li><a href=\"matches.html\" class=\"nav-link\">Matches</a></li>\r\n");
      out.write("                <li><a href=\"players.html\" class=\"nav-link\">Players</a></li>\r\n");
      out.write("                <li><a href=\"blog.html\" class=\"nav-link\">Mypage</a></li>\r\n");
      out.write("                <li><a href=\"/Logout.do\" class=\"nav-link\">Logout</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("\r\n");
      out.write("            <a href=\"#\" class=\"d-inline-block d-lg-none site-menu-toggle js-menu-toggle text-black float-right text-white\"><span\r\n");
      out.write("                class=\"icon-menu h3 text-white\"></span></a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"hero overlay\" style=\"background-image: url('images/bg_3.jpg');\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row align-items-center\">\r\n");
      out.write("          <div class=\"col-lg-5 ml-auto\">\r\n");
      out.write("            <h1 class=\"text-white\">World Cup Event</h1>\r\n");
      out.write("            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta, molestias repudiandae pariatur.</p>\r\n");
      out.write("            <div id=\"date-countdown\"></div>\r\n");
      out.write("            <p>\r\n");
      out.write("              <a href=\"#\" class=\"btn btn-primary py-3 px-4 mr-3\">Book Ticket</a>\r\n");
      out.write("              <a href=\"#\" class=\"more light\">Learn More</a>\r\n");
      out.write("            </p>  \r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-lg-12\">\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"d-flex team-vs\">\r\n");
      out.write("            <span class=\"score\">4-1</span>\r\n");
      out.write("            <div class=\"team-1 w-50\">\r\n");
      out.write("              <div class=\"team-details w-100 text-center\">\r\n");
      out.write("                <img src=\"../reousrce/images/logo_1.png\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("                <h3>LA LEGA <span>(win)</span></h3>\r\n");
      out.write("                <ul class=\"list-unstyled\">\r\n");
      out.write("                  <li>Anja Landry (7)</li>\r\n");
      out.write("                  <li>Eadie Salinas (12)</li>\r\n");
      out.write("                  <li>Ashton Allen (10)</li>\r\n");
      out.write("                  <li>Baxter Metcalfe (5)</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"team-2 w-50\">\r\n");
      out.write("              <div class=\"team-details w-100 text-center\">\r\n");
      out.write("                <img src=\"../resource/images/logo_2.png\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("                <h3>JUVENDU <span>(loss)</span></h3>\r\n");
      out.write("                <ul class=\"list-unstyled\">\r\n");
      out.write("                  <li>Macauly Green (3)</li>\r\n");
      out.write("                  <li>Arham Stark (8)</li>\r\n");
      out.write("                  <li>Stephan Murillo (9)</li>\r\n");
      out.write("                  <li>Ned Ritter (5)</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("    <div class=\"latest-news\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-12 title-section\">\r\n");
      out.write("            <h2 class=\"heading\">Latest News</h2>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row no-gutters\">\r\n");
      out.write("          <div class=\"col-md-4\">\r\n");
      out.write("            <div class=\"post-entry\">\r\n");
      out.write("              <a href=\"#\">\r\n");
      out.write("                <img src=\"images/img_1.jpg\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"caption\">\r\n");
      out.write("                <div class=\"caption-inner\">\r\n");
      out.write("                  <h3 class=\"mb-3\">Romolu to stay at Real Nadrid?</h3>\r\n");
      out.write("                  <div class=\"author d-flex align-items-center\">\r\n");
      out.write("                    <div class=\"img mb-2 mr-3\">\r\n");
      out.write("                      <img src=\"images/person_1.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"text\">\r\n");
      out.write("                      <h4>Mellissa Allison</h4>\r\n");
      out.write("                      <span>May 19, 2020 &bullet; Sports</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div> \r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4\">\r\n");
      out.write("            <div class=\"post-entry\">\r\n");
      out.write("              <a href=\"#\">\r\n");
      out.write("                <img src=\"images/img_3.jpg\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"caption\">\r\n");
      out.write("                <div class=\"caption-inner\">\r\n");
      out.write("                  <h3 class=\"mb-3\">Kai Nets Double To Secure Comfortable Away Win</h3>\r\n");
      out.write("                  <div class=\"author d-flex align-items-center\">\r\n");
      out.write("                    <div class=\"img mb-2 mr-3\">\r\n");
      out.write("                      <img src=\"images/person_1.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"text\">\r\n");
      out.write("                      <h4>Mellissa Allison</h4>\r\n");
      out.write("                      <span>May 19, 2020 &bullet; Sports</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div> \r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4\">\r\n");
      out.write("            <div class=\"post-entry\">\r\n");
      out.write("              <a href=\"#\">\r\n");
      out.write("                <img src=\"images/img_2.jpg\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"caption\">\r\n");
      out.write("                <div class=\"caption-inner\">\r\n");
      out.write("                  <h3 class=\"mb-3\">Dogba set for Juvendu return?</h3>\r\n");
      out.write("                  <div class=\"author d-flex align-items-center\">\r\n");
      out.write("                    <div class=\"img mb-2 mr-3\">\r\n");
      out.write("                      <img src=\"images/person_1.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"text\">\r\n");
      out.write("                      <h4>Mellissa Allison</h4>\r\n");
      out.write("                      <span>May 19, 2020 &bullet; Sports</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div> \r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"site-section bg-dark\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-lg-6\">\r\n");
      out.write("            <div class=\"widget-next-match\">\r\n");
      out.write("              <div class=\"widget-title\">\r\n");
      out.write("                <h3>Next Match</h3>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"widget-body mb-3\">\r\n");
      out.write("                <div class=\"widget-vs\">\r\n");
      out.write("                  <div class=\"d-flex align-items-center justify-content-around justify-content-between w-100\">\r\n");
      out.write("                    <div class=\"team-1 text-center\">\r\n");
      out.write("                      <img src=\"../reousrce/images/logo_1.png\" alt=\"Image\">\r\n");
      out.write("                      <h3>Football League</h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                      <span class=\"vs\"><span>VS</span></span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"team-2 text-center\">\r\n");
      out.write("                      <img src=\"../reousrce/images/logo_2.png\" alt=\"Image\">\r\n");
      out.write("                      <h3>Soccer</h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"text-center widget-vs-contents mb-4\">\r\n");
      out.write("                <h4>World Cup League</h4>\r\n");
      out.write("                <p class=\"mb-5\">\r\n");
      out.write("                  <span class=\"d-block\">December 20th, 2020</span>\r\n");
      out.write("                  <span class=\"d-block\">9:30 AM GMT+0</span>\r\n");
      out.write("                  <strong class=\"text-primary\">New Euro Arena</strong>\r\n");
      out.write("                </p>\r\n");
      out.write("\r\n");
      out.write("                <div id=\"date-countdown2\" class=\"pb-1\"></div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-6\">\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"widget-next-match\">\r\n");
      out.write("              <table class=\"table custom-table\">\r\n");
      out.write("                <thead>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <th>P</th>\r\n");
      out.write("                    <th>Team</th>\r\n");
      out.write("                    <th>W</th>\r\n");
      out.write("                    <th>D</th>\r\n");
      out.write("                    <th>L</th>\r\n");
      out.write("                    <th>PTS</th>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>1</td>\r\n");
      out.write("                    <td><strong class=\"text-white\">Football League</strong></td>\r\n");
      out.write("                    <td>22</td>\r\n");
      out.write("                    <td>3</td>\r\n");
      out.write("                    <td>2</td>\r\n");
      out.write("                    <td>140</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>2</td>\r\n");
      out.write("                    <td><strong class=\"text-white\">Soccer</strong></td>\r\n");
      out.write("                    <td>22</td>\r\n");
      out.write("                    <td>3</td>\r\n");
      out.write("                    <td>2</td>\r\n");
      out.write("                    <td>140</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>3</td>\r\n");
      out.write("                    <td><strong class=\"text-white\">Juvendo</strong></td>\r\n");
      out.write("                    <td>22</td>\r\n");
      out.write("                    <td>3</td>\r\n");
      out.write("                    <td>2</td>\r\n");
      out.write("                    <td>140</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>4</td>\r\n");
      out.write("                    <td><strong class=\"text-white\">French Football League</strong></td>\r\n");
      out.write("                    <td>22</td>\r\n");
      out.write("                    <td>3</td>\r\n");
      out.write("                    <td>2</td>\r\n");
      out.write("                    <td>140</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>5</td>\r\n");
      out.write("                    <td><strong class=\"text-white\">Legia Abante</strong></td>\r\n");
      out.write("                    <td>22</td>\r\n");
      out.write("                    <td>3</td>\r\n");
      out.write("                    <td>2</td>\r\n");
      out.write("                    <td>140</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>6</td>\r\n");
      out.write("                    <td><strong class=\"text-white\">Gliwice League</strong></td>\r\n");
      out.write("                    <td>22</td>\r\n");
      out.write("                    <td>3</td>\r\n");
      out.write("                    <td>2</td>\r\n");
      out.write("                    <td>140</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>7</td>\r\n");
      out.write("                    <td><strong class=\"text-white\">Cornika</strong></td>\r\n");
      out.write("                    <td>22</td>\r\n");
      out.write("                    <td>3</td>\r\n");
      out.write("                    <td>2</td>\r\n");
      out.write("                    <td>140</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>8</td>\r\n");
      out.write("                    <td><strong class=\"text-white\">Gravity Smash</strong></td>\r\n");
      out.write("                    <td>22</td>\r\n");
      out.write("                    <td>3</td>\r\n");
      out.write("                    <td>2</td>\r\n");
      out.write("                    <td>140</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                </tbody>\r\n");
      out.write("              </table>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div> <!-- .site-section -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"site-section\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-6 title-section\">\r\n");
      out.write("            <h2 class=\"heading\">Videos</h2>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-6 text-right\">\r\n");
      out.write("            <div class=\"custom-nav\">\r\n");
      out.write("            <a href=\"#\" class=\"js-custom-prev-v2\"><span class=\"icon-keyboard_arrow_left\"></span></a>\r\n");
      out.write("            <span></span>\r\n");
      out.write("            <a href=\"#\" class=\"js-custom-next-v2\"><span class=\"icon-keyboard_arrow_right\"></span></a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"owl-4-slider owl-carousel\">\r\n");
      out.write("          <div class=\"item\">\r\n");
      out.write("            <div class=\"video-media\">\r\n");
      out.write("              <img src=\"../reousrce/images/img_1.jpg\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("              <a href=\"https://vimeo.com/139714818\" class=\"d-flex play-button align-items-center\" data-fancybox>\r\n");
      out.write("                <span class=\"icon mr-3\">\r\n");
      out.write("                  <span class=\"icon-play\"></span>\r\n");
      out.write("                </span>\r\n");
      out.write("                <div class=\"caption\">\r\n");
      out.write("                  <h3 class=\"m-0\">Dogba set for Juvendu return?</h3>\r\n");
      out.write("                </div>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"item\">\r\n");
      out.write("            <div class=\"video-media\">\r\n");
      out.write("              <img src=\"../reousrce/images/img_2.jpg\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("              <a href=\"https://vimeo.com/139714818\" class=\"d-flex play-button align-items-center\" data-fancybox>\r\n");
      out.write("                <span class=\"icon mr-3\">\r\n");
      out.write("                  <span class=\"icon-play\"></span>\r\n");
      out.write("                </span>\r\n");
      out.write("                <div class=\"caption\">\r\n");
      out.write("                  <h3 class=\"m-0\">Kai Nets Double To Secure Comfortable Away Win</h3>\r\n");
      out.write("                </div>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"item\">\r\n");
      out.write("            <div class=\"video-media\">\r\n");
      out.write("              <img src=\"../reousrce/images/img_3.jpg\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("              <a href=\"https://vimeo.com/139714818\" class=\"d-flex play-button align-items-center\" data-fancybox>\r\n");
      out.write("                <span class=\"icon mr-3\">\r\n");
      out.write("                  <span class=\"icon-play\"></span>\r\n");
      out.write("                </span>\r\n");
      out.write("                <div class=\"caption\">\r\n");
      out.write("                  <h3 class=\"m-0\">Romolu to stay at Real Nadrid?</h3>\r\n");
      out.write("                </div>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"item\">\r\n");
      out.write("            <div class=\"video-media\">\r\n");
      out.write("              <img src=\"../reousrce/images/img_1.jpg\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("              <a href=\"https://vimeo.com/139714818\" class=\"d-flex play-button align-items-center\" data-fancybox>\r\n");
      out.write("                <span class=\"icon mr-3\">\r\n");
      out.write("                  <span class=\"icon-play\"></span>\r\n");
      out.write("                </span>\r\n");
      out.write("                <div class=\"caption\">\r\n");
      out.write("                  <h3 class=\"m-0\">Dogba set for Juvendu return?</h3>\r\n");
      out.write("                </div>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"item\">\r\n");
      out.write("            <div class=\"video-media\">\r\n");
      out.write("              <img src=\"../reousrce/images/img_2.jpg\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("              <a href=\"https://vimeo.com/139714818\" class=\"d-flex play-button align-items-center\" data-fancybox>\r\n");
      out.write("                <span class=\"icon mr-3\">\r\n");
      out.write("                  <span class=\"icon-play\"></span>\r\n");
      out.write("                </span>\r\n");
      out.write("                <div class=\"caption\">\r\n");
      out.write("                  <h3 class=\"m-0\">Kai Nets Double To Secure Comfortable Away Win</h3>\r\n");
      out.write("                </div>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"item\">\r\n");
      out.write("            <div class=\"video-media\">\r\n");
      out.write("              <img src=\"../reousrce/images/img_3.jpg\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("              <a href=\"https://vimeo.com/139714818\" class=\"d-flex play-button align-items-center\" data-fancybox>\r\n");
      out.write("                <span class=\"icon mr-3\">\r\n");
      out.write("                  <span class=\"icon-play\"></span>\r\n");
      out.write("                </span>\r\n");
      out.write("                <div class=\"caption\">\r\n");
      out.write("                  <h3 class=\"m-0\">Romolu to stay at Real Nadrid?</h3>\r\n");
      out.write("                </div>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container site-section\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-6 title-section\">\r\n");
      out.write("          <h2 class=\"heading\">Our Blog</h2>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-lg-6\">\r\n");
      out.write("          <div class=\"custom-media d-flex\">\r\n");
      out.write("            <div class=\"img mr-4\">\r\n");
      out.write("              <img src=\"../reousrce/images/img_1.jpg\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"text\">\r\n");
      out.write("              <span class=\"meta\">May 20, 2020</span>\r\n");
      out.write("              <h3 class=\"mb-4\"><a href=\"#\">Romolu to stay at Real Nadrid?</a></h3>\r\n");
      out.write("              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus deserunt saepe tempora dolorem.</p>\r\n");
      out.write("              <p><a href=\"#\">Read more</a></p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-lg-6\">\r\n");
      out.write("          <div class=\"custom-media d-flex\">\r\n");
      out.write("            <div class=\"img mr-4\">\r\n");
      out.write("              <img src=\"../reousrce/images/img_3.jpg\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"text\">\r\n");
      out.write("              <span class=\"meta\">May 20, 2020</span>\r\n");
      out.write("              <h3 class=\"mb-4\"><a href=\"#\">Romolu to stay at Real Nadrid?</a></h3>\r\n");
      out.write("              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus deserunt saepe tempora dolorem.</p>\r\n");
      out.write("              <p><a href=\"#\">Read more</a></p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <footer class=\"footer-section\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-lg-3\">\r\n");
      out.write("            <div class=\"widget mb-3\">\r\n");
      out.write("              <h3>News</h3>\r\n");
      out.write("              <ul class=\"list-unstyled links\">\r\n");
      out.write("                <li><a href=\"#\">All</a></li>\r\n");
      out.write("                <li><a href=\"#\">Club News</a></li>\r\n");
      out.write("                <li><a href=\"#\">Media Center</a></li>\r\n");
      out.write("                <li><a href=\"#\">Video</a></li>\r\n");
      out.write("                <li><a href=\"#\">RSS</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-3\">\r\n");
      out.write("            <div class=\"widget mb-3\">\r\n");
      out.write("              <h3>Tickets</h3>\r\n");
      out.write("              <ul class=\"list-unstyled links\">\r\n");
      out.write("                <li><a href=\"#\">Online Ticket</a></li>\r\n");
      out.write("                <li><a href=\"#\">Payment and Prices</a></li>\r\n");
      out.write("                <li><a href=\"#\">Contact &amp; Booking</a></li>\r\n");
      out.write("                <li><a href=\"#\">Tickets</a></li>\r\n");
      out.write("                <li><a href=\"#\">Coupon</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-3\">\r\n");
      out.write("            <div class=\"widget mb-3\">\r\n");
      out.write("              <h3>Matches</h3>\r\n");
      out.write("              <ul class=\"list-unstyled links\">\r\n");
      out.write("                <li><a href=\"#\">Standings</a></li>\r\n");
      out.write("                <li><a href=\"#\">World Cup</a></li>\r\n");
      out.write("                <li><a href=\"#\">La Lega</a></li>\r\n");
      out.write("                <li><a href=\"#\">Hyper Cup</a></li>\r\n");
      out.write("                <li><a href=\"#\">World League</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-lg-3\">\r\n");
      out.write("            <div class=\"widget mb-3\">\r\n");
      out.write("              <h3>Social</h3>\r\n");
      out.write("              <ul class=\"list-unstyled links\">\r\n");
      out.write("                <li><a href=\"#\">Twitter</a></li>\r\n");
      out.write("                <li><a href=\"#\">Facebook</a></li>\r\n");
      out.write("                <li><a href=\"#\">Instagram</a></li>\r\n");
      out.write("                <li><a href=\"#\">Youtube</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row text-center\">\r\n");
      out.write("          <div class=\"col-md-12\">\r\n");
      out.write("            <div class=\" pt-5\">\r\n");
      out.write("              <p>\r\n");
      out.write("                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("                Copyright &copy;\r\n");
      out.write("                <script>\r\n");
      out.write("                  document.write(new Date().getFullYear());\r\n");
      out.write("                </script> All rights reserved | This template is made with <i class=\"icon-heart\"\r\n");
      out.write("                  aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("              </p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- .site-wrap -->\r\n");
      out.write("\r\n");
      out.write("  <script src=\"../resource/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("  <script src=\"../resource/js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("  <script src=\"../resource/js/jquery-ui.js\"></script>\r\n");
      out.write("  <script src=\"../resource/js/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"../resource/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <script src=\"../resource/js/owl.carousel.min.js\"></script>\r\n");
      out.write("  <script src=\"../resource/js/jquery.stellar.min.js\"></script>\r\n");
      out.write("  <script src=\"../resource/js/jquery.countdown.min.js\"></script>\r\n");
      out.write("  <script src=\"../resource/js/bootstrap-datepicker.min.js\"></script>\r\n");
      out.write("  <script src=\"../resource/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("  <script src=\"../resource/js/aos.js\"></script>\r\n");
      out.write("  <script src=\"../resource/js/jquery.fancybox.min.js\"></script>\r\n");
      out.write("  <script src=\"../resource/js/jquery.sticky.js\"></script>\r\n");
      out.write("  <script src=\"../resource/js/jquery.mb.YTPlayer.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <script src=\"../resource/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
